import Hero from "@/app/(management)/teams/Hero";
import Footer from "@/components/Footer";
import MainTitle from "@/components/MainTitle";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Our team",
	description: "Generated by create next app",
};
const Teams = (): JSX.Element => {
	return (
		<>
			<main>
				<MainTitle heading={"Our Team"} />
				<Hero />
			</main>
			<Footer />
		</>
	);
};

export default Teams;
